warning_threshold: 15
type_body_length: 150


closure_body_length:
  error: 40
  warning: 20
  
cyclomatic_complexity:
  error: 20
  warning: 14
  
  
file_length:
  error: 500
  warning: 400
  
function_body_length:
  error: 70
  warning: 50
  
function_parameter_count:
 error: 7
 warning: 5
 
   
identifier_name:
  min_length:
    error: 2
    warning: 2
  max_length:
    error: 50
    warning: 40
  excluded:
    - i

  
large_tuple:
  error: 6
  warning: 5
 
line_length:
  error: 350
  warning: 260
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: false
  

nesting:
  type_level: 2
  statement_level: 4
  

private_outlet:
  allow_private_set: true


type_name:
  min_length:
    error: 2
    warning: 3
  max_length:
    error: 50
    warning: 40
    
  
vertical_whitespace:
  max_empty_lines: 3


opt_in_rules:
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_declaration
  - yoda_condition

disabled_rules:
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
  - void_return
  
excluded:
  - Frameworks
  - Libraries
  - Pods
  - Products
  - Style
  
