# Uncomment this line to define a global platform for your project

platform :ios, '10.0'
project 'EnvironmentSwitcherExample.xcodeproj'
use_frameworks!

def shared_pods
    pod 'EnvironmentSwitcher', :git => 'https://github.com/StasanTelnov/EnvironmentSwither.git'
end

target 'EnvironmentSwitcherExample' do
    shared_pods
end

target 'EnvironmentSwitcherExampleTests' do
    inherit! :search_paths
    shared_pods
end

target 'EnvironmentSwitcherExampleUITests' do
    inherit! :search_paths
    shared_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
        end
    end
end